<a href="https://colab.research.google.com/github/HarshadKumbhar0822/Data_Associate/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#(2,3,2,3)
# 4d array use of numpy

arr = np.array([[[[1,2,3],[11,12,13]]]])
print(arr.shape)
print(arr.ndim)

(1, 1, 2, 3)
4


In [ ]:


# Generate 4d array (4,3,2,1)
arr_new = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],
                    [[[7],[8]],[[9],[10]],[[11],[12]]],
                    [[[13],[14]],[[15],[16]],[[17],[18]]],
                    [[[19],[20]],[[21],[22]],[[23],[24]]]])
print(arr_new.shape)
print(arr_new.ndim)


(4, 3, 2, 1)
4


In [ ]:
arrr = np.array([[[[6],[9]],[[6],[9]],[[6],[9]]],[[[6],[9]],[[6],[9]],[[6],[9]]],[[[6],[9]],[[6],[9]],[[6],[9]]],[[[6],[9]],[[6],[9]],[[6],[9]]]])
print(arrr.shape)
print(arrr.ndim)

(4, 3, 2, 1)
4


In [ ]:
arr = np.array([[4,5],[2,9]])
print(arr[0:2,1:])

[[5]
 [9]]


In [ ]:
arr = np.ones((3,3), 'int32')
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
arr = np.zeros((3,3), 'int32')
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
arr = np.full((3,3,2), 99, 'int32')
print(arr)

[[[99 99]
  [99 99]
  [99 99]]

 [[99 99]
  [99 99]
  [99 99]]

 [[99 99]
  [99 99]
  [99 99]]]


In [ ]:
arr = np.eye(5,5)
print(arr)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import pandas as pd
arr = np.random.random((3,3)).reshape(9,)
df = pd.Series(arr)
print(df)

0    0.635471
1    0.494663
2    0.890886
3    0.160488
4    0.300296
5    0.006472
6    0.369782
7    0.828335
8    0.936165
dtype: float64


In [ ]:
arr = np.random.randint(1,100,(2,10))
print(arr)

[[62 60 39 57 83 30 34 37  1 27]
 [29 80 19 88 11 34 33 35 36 31]]


In [ ]:
arr = np.arange(1,2)
arr1 = np.arange(3,6,1)
arr1

array([3, 4, 5])

In [ ]:
lst = [4,5,6,7]
lst * 2

[4, 5, 6, 7, 4, 5, 6, 7]

In [ ]:
arr = np.array([4,5,6,7])
arr * 2

array([ 8, 10, 12, 14])

In [ ]:
np.arange(4
          )

In [ ]:
np.linspace(1,10,7)


array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [ ]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [ ]:
arr = np.array([9,23,2,3,4,5,67])
np.sort(arr)

array([ 2,  3,  4,  5,  9, 23, 67])

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([[[4,6,5],[2,3,4],[7,9,0]]])

a.shape

(1, 3, 3)

In [ ]:
a = np.arange(24).reshape(1,4,-1)
print(a.shape)

(1, 4, 6)


In [ ]:
# add new axis = np.axis

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a.shape)

(6,)


In [ ]:
a2 = a[: ,np.newaxis]
print(a2.shape)

(6, 1)


In [ ]:
b = np.expand_dims(a, axis=1)
print(b.shape)

(6, 1)


In [ ]:
a = np.array([[1,2,3,4,5,6],[2,6,8,99,4,5],[33,5,44,33,22,22]])
print(a.shape)

(3, 6)


In [ ]:
b = a[a > 5]
print(b)

[ 6  6  8 99 33 44 33 22 22]


In [ ]:
c = a[(a > 5) & (a < 20)]
print(c)


[6 6 8]


In [ ]:
d = (a > 88) | (a < 20)
print(d)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [False  True False False False False]]


In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [ ]:
# Original vector
vector = [1, 2, 3, 4, 5]

# Reversed vector using slicing
reversed_vector = vector[::-1]

print(reversed_vector)


[5, 4, 3, 2, 1]


In [ ]:
import numpy as np

# Create a 3x3 matrix with values from 0 to 8
matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# prompt: create 2d array with 1 on border inside 0

import numpy as np

def border_array(rows, cols):
  """Creates a 2D array with 1s on the border and 0s inside.

  Args:
    rows: The number of rows in the array.
    cols: The number of columns in the array.

  Returns:
    A NumPy array with the specified pattern.
  """

  arr = np.zeros((rows, cols), dtype=int)  # Initialize with zeros
  arr[0, :] = 1  # Top row
  arr[-1, :] = 1  # Bottom row
  arr[:, 0] = 1  # Left column
  arr[:, -1] = 1  # Right column
  return arr

# Example usage:
rows = 5
cols = 5
result = border_array(rows, cols)
print(result)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
# prompt: chess pattern black = 1and white=0

import numpy as np

def chess_pattern(rows, cols):
  """Creates a chessboard pattern with 1s for black and 0s for white.

  Args:
    rows: The number of rows in the chessboard.
    cols: The number of columns in the chessboard.

  Returns:
    A NumPy array representing the chessboard pattern.
  """

  chessboard = np.zeros((rows, cols), dtype=int)
  chessboard[::2, ::2] = 1  # Set every other square to 1, starting from top-left
  chessboard[1::2, 1::2] = 1  # Set every other square to 1, starting from second row, second column
  return chessboard

# Example usage:
rows = 8
cols = 8
result = chess_pattern(rows, cols)
print(result)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
z = np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


=

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [ ]:
a = np.arange(336).reshape(6,7,8)
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15